version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - arthurgeron
  - auvred
  - biscuittin
  - bttin
  - callees
  - cjsx
  - commitlint
  - dprint
  - eslintcache
  - gplane
  - hasown
  - Intelli
  - malva
  - micromark
  - mjsx
  - multilines
  - nolyfill
  - nonconstructor
  - postc
  - postpublish
  - proptypes
  - sukka
  - Syncify
  - textnodes
  - tsconfigs
  - tsdown
  - typegen
  - Vali
  - valibot
ignoreWords: []
import: []
